[font]
size = 12

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[terminal.shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/opt/homebrew/bin/fish"
# program = "/bin/zsh"

[colors.primary]
background = "#24283b"
foreground = "#9aa5ce"
